apiVersion: v1
kind: Service
metadata:
  labels:
    app: ballerina-playground-gists
  name: ballerina-playground-gists-service
spec:
  ports:
    - name: "web-port-http"
      port: 80
      targetPort: 9090
  selector:
    app: ballerina-playground-gists

