apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballerina-playground-executor-deployment
  labels:
    app: ballerina-playground-executor
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ballerina-playground-executor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ballerina-playground-executor
    spec:
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: pvc-build-cache-rw
      containers:
      - name: ballerina-playground-executor-container
        imagePullPolicy: Always
        image: gcr.io/${BPG_GCP_PROJECT_ID}/playground-executor:${RELEASE_VERSION}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: pvc-nfs
          mountPath: "/build-cache"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9090
          