apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-build-cache
spec:
  storageClassName: build.cache
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.${BPG_NAMESPACE}.svc.cluster.local
    path: "/exports"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-build-cache-rw
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: build.cache
  resources:
    requests:
      storage: 100Gi