apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballerina-playground-compiler-deployment
  labels:
    app: ballerina-playground-compiler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ballerina-playground-compiler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ballerina-playground-compiler
    spec:
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: pvc-build-cache-rw
      containers:
      - name: ballerina-playground-compiler-container
        imagePullPolicy: Always
        image: gcr.io/${BPG_GCP_PROJECT_ID}/playground-compiler:${RELEASE_VERSION}
        volumeMounts:
        - name: pvc-nfs
          mountPath: "/build-cache"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9090
          